#For creating docker container with parsing services
services:
  flask_app:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - CUDA_VISIBLE_DEVICES=""
      - FLASK_APP=preprocessing_api.py
      - FLASK_ENV=development