accelerate launch train_trl_cot.py \
    --model deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B \
    --dataset ./data/sprint_goals_training_data-qwen-3B.jsonl \
    --output_dir ./trl_checkpoints_exploratory \
    --epochs 10 \
    --lr 3e-6 \
    --temperature 0.6 \
    --top_p 0.95 \
    --max_completion_length 1024 \
    --beta 0.05 \
    --epsilon 0.3 \
    --save_strategy epoch \
    --batch_size 5 \
    --gradient_accumulation_steps 9 \
    --gradient_checkpointing \
    --bf16 \
    --logging_steps 5 \
    --log_completions \
    --num_completions_to_print 4 \
    --num_generations 3 \
    --num_iterations 4