accelerate launch train_trl_cot.py \
    --model deepseek-ai/DeepSeek-R1-Distill-Qwen-14B \
    --dataset ./data/sprint_goals_training_data-qwen-3B.jsonl \
    --output_dir ./trl_checkpoints_lora_14B \
    --epochs 10 \
    --lr 3e-6 \
    --temperature 0.6 \
    --top_p 0.95 \
    --max_completion_length 1024 \
    --beta 0.1 \
    --epsilon 0.25 \
    --save_strategy epoch \
    --batch_size 6 \
    --gradient_accumulation_steps 16 \
    --logging_steps 5 \
    --log_completions \
    --gradient_checkpointing \
    --num_completions_to_print 4 \
    --num_generations 3 \
    --load_4bit \
    --num_iterations 4 \
    --lora_dropout 0.05 \
    --lora_r 16 \
    --lora_alpha 32 \
